version: '3.4'

networks:
  proxy:
    external: true

services:
  greatleaderxibot:
    image: temurka1/greatleaderxibot
    restart: always
    networks:
      - proxy
    env_file:
      - ./vars.env
    build:
      context: .
      dockerfile: GreatLeaderXiBot/Dockerfile
