name: build and publish docker containers

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3

      - 
        name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: build&publish docker image
        uses: docker/build-push-action@v2
        with:
          context: source/GreatLeaderXiBot/
          push: true
          tags: temurka1/greatleaderxibot:latest

      #-
      #  name: deploy
      #  uses: appleboy/ssh-action@master
      #  env:
      #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #    HOST: ${{ secrets.DEPLOY_HOST }}
      #    EMAIL: ${{ secrets.EMAIL }}
      #  with:
      #    host: ${{ secrets.DEPLOY_HOST }}
      #    port: 22
      #    username: ${{ secrets.DEPLOY_USER }}
      #    key: ${{ secrets.DEPLOY_KEY }}
      #    envs: DOCKER_USERNAME, DOCKER_PASSWORD, HOST, EMAIL
      #    script: |
      #      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #      docker stop greatleaderxi_bot
      #      docker rm greatleaderxi_bot
      #      docker rmi temurka1/greatleaderxibot
      #      docker run -d -e VIRTUAL_HOST=$HOST -e LETSENCRYPT_HOST=$HOST -e LETSENCRYPT_EMAIL=$EMAIL --network=proxy --name greatleaderxi_bot temurka1/greatleaderxibot:latest --restart=always